### ISSUE TITLE
Form of source terms and other indexing

### ISSUE THREAD

**Issue by ranocha** [trixi-gpu/TrixiCUDA.jl#1]
I'm not sure whether the implementation

https://github.com/huiyuxie/trixi_cuda/blob/13f4ec8ecb579412c04d4a024465711ff5cd89f5/source_terms.jl#L42-L44

is correct. In Trixi.jl on CPUs, we have a memory layout of the form

```
u[number_of_variables, number_of_nodes, number_of_elements]
```

in 1D. Here, the `number_of_variables` refers to the number of variables of the PDE, e.g.,
- 1 for the scalar linear advection equation
- 3 for the ideal compressible Euler equations in 1D (density, momentum, and energy)

We need all of the variables from the first dimension of `u` at a single node specified by the index running through `1:number_of_nodes` and `1:number_of_elements`. Thus, what we have on CPUs looks more like

```julia
for element in eachelement(dg, cache) # loop over third dimension of u
    for i in eachnode(dg) # loop over second dimension of u
        # collect everything from the first dimension of u with further indices `i, element`
        # in an `SVector` from StaticArrays.jl in a type-stable way
        u_local = get_node_vars(u, equations, dg, i, element)
        # Now, we have
        # for var in axes(u, 1)
        #     u_local[var] == u[var, i, element]
        # end

        # Same for the spatial coordinates
        x_local = get_node_coords(cache.elements.node_coordinates, equations, dg, i,
                                  element)

        # Compute the pointwise source terms at the spatial location specified by the indices `i, element`
        du_local = source_terms(u_local, x_local, t, equations)

        # This is basically the same as
        # for var in axes(u, 1)
        #     du[var, i, element] = du_local[var]
        # end
        add_to_node_vars!(du, du_local, equations, dg, i, element)
    end
end

du[i, j, k] += source_terms(u[i, j, k], node_coordinates[1, j, k], t, equations)
```

**Comment by ranocha** [comment]
Something similar happens for

https://github.com/huiyuxie/trixi_cuda/blob/13f4ec8ecb579412c04d4a024465711ff5cd89f5/linear_advection_1d.jl#L87-L89

This will work fine for linear advection with just a single variable. However, it should also collect something like

```julia
u_node = SVector(u[:, i, element])
```

in a type-stable way as we do in `get_node_vars` and pass it to `flux`. Then, the update of `du` should distribute the return value of `flux` over the first indices of `du` with fixed second and third indices `i, element`.

**Comment by ranocha** [comment]
The `weak_form_kernel!` with

https://github.com/huiyuxie/trixi_cuda/blob/13f4ec8ecb579412c04d4a024465711ff5cd89f5/linear_advection_1d.jl#L101-L103

is fine.

**Comment by ranocha** [comment]
Similar changes are required for the `surface_flux_kernel!` in

https://github.com/huiyuxie/trixi_cuda/blob/13f4ec8ecb579412c04d4a024465711ff5cd89f5/linear_advection_1d.jl#L161-L163

**Comment by ranocha** [comment]
It would be great if you could test your implementation against the CPU version implemented in Trixi.jl for
- the linear advection equation (where it should work already since it's a scalar equation with a single variable)
- the compressible Euler equations, e.g., https://github.com/trixi-framework/Trixi.jl/blob/main/examples/tree_1d_dgsem/elixir_euler_source_terms.jl

**Comment by huiyuxie** [comment]
Thanks for opening the issue! It has already been fixed.

**Comment by huiyuxie** [comment]
Thanks for opening the issue!
